### ISSUE TITLE
No new version created when modifying Alfresco document

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#210]
Steps:
1. Create a site in Alfresco Share, with aspect Versionning activated
2. Create a document
3. Sync with CmisSync
4. Modify the document on the CmisSync side
5. See that the document's is correctly updated
6. See that the document appears in Alfresco Share's activity stream of recently modified documents
7. See that version number has not been increased, there is only one version of the document.

**Comment by mathieuga** [comment]
For information,
In my Alfresco Setting ".docx" have versionable aspect properties "Auto Version - on update properties onlyValeur" to "true" and "Version automatiqueValeur" to "true".
But ".pdf" have versionable aspect properties "Auto Version - on update properties onlyValeur" to "false" and "Version automatiqueValeur" to "false".

So to simply force Alfresco to create a new version for each change I add a Rule that 
- add the cm:versionable aspect
- set properties :Auto Version - on update properties onlyValeur:true
- set properties : Version automatiqueValeur:true

Think Nicolas for this great tool !
