### ISSUE TITLE
Modifying location of local copy

### ISSUE THREAD

**Issue by wimco** [aegif/CmisSync#219]
I want to use a custom path to keep the local copy of the repo.

I am scanning to a folder c:\scans.  Some local workflow happens and the files go to c:\scans\sorted.  I want to synchronize this folder with my Alfresco.

In the \Application Data\cmissync\config.xml,
Modifying the <folders>    <folder>      <path> tag causes the program to crash if the <path> tag is non-standard.

Can it be made configurable?

**Comment by nicolas-raoul** [comment]
I guess this works now? If not please reopen, thanks!
