### ISSUE TITLE
Server to local syncing problem with Nuxeo

### ISSUE THREAD

**Issue by pibou** [aegif/CmisSync#239]
Description of the issue :
I set up a new connection to my nuxeo server
I choose a folder to sync upon which the connected user has RW rights
(the folder is empty)
the local shared folder is created

locally, i create the "local dir" directory : it is uploaded to Nuxeo
on Nuxeo, i create the "nux dir" directory : it is downloaded to the synced folder

locally, i create the "local picture" file : it is uploaded to Nuxeo but disappears from the local folder once the synchonisation has occured
on Nuxeo, i create the "nux picture" file : it is not downloaded to the synced folder

Extract from log :

```
2013-09-10 09:16:28,766 [4] INFO  CmisSync.Lib.Sync.CmisRepo [(null)] - New remote file: C:\Users\bouvret\CmisSync\xxxx\local file.bmp
2013-09-10 09:16:28,766 [4] INFO  CmisSync.Lib.Sync.CmisRepo [(null)] - Downloading: local file.bmp
2013-09-10 09:16:28,937 [4] INFO  CmisSync.Lib.Sync.CmisRepo [(null)] - Downloaded: local file.bmp
2013-09-10 09:16:28,937 [4] INFO  CmisSync.Lib.Sync.CmisRepo [(null)] - Exception while fetching metadata: local file.bmp Exception:
La référence d'objet n'est pas définie à une instance d'un objet.
StackTrace:
   à DotCMIS.Client.Impl.Property.get_ValuesAsString()
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.FetchMetadata(IDocument document)
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument remoteDocument, String localFolder)
Source:
DotCMIS
TargetSite:
System.String get_ValuesAsString()
BaseException:
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à DotCMIS.Client.Impl.Property.get_ValuesAsString()
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.FetchMetadata(IDocument document)
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument remoteDocument, String localFolder)
```

**Comment by nicolas-raoul** [comment]
CmisSync and Nuxeo have changed a lot in 2 years, it seems that this problem got fixed.
If anyone still observe this problem, please don't hesitate to reopen.
Cheers!
Nicolas
