### ISSUE TITLE
Self-signed SSL certificate: CmisSync keeps asking for confirmation

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#255]
By Jonathan on mailing list:

I have a self-signed SSL certificate,
and when I add a new file or folder,
I constantly Untrusted Certificate dialog box
when I click yes to remember that this, he returns to me anyway.
Is there a possibility to accept once and for all?

![capture](https://f.cloud.github.com/assets/99590/1426692/626bc28a-4074-11e3-8009-c5e51d3fc8f1.PNG)

**Comment by antton** [comment]
From one week ago, I'm having this problem. on one computer with 2.3.3 version. The other workmates with this version are not having this problems and it's strange, the only difference from this user and the others is that I create manually on config.xml file the folder entries. I'm gonna try to upgrade the version even if is not the real problem of it.

**Comment by nicolas-raoul** [comment]
Strange, creating manually config.xml should be exactly the same as going via the wizard...

**Comment by antton** [comment]
yes it is, I let you know after upgrade the version.

**Comment by antton** [comment]
I install the cert on windows as trusted certificate entitie and I think that the problem is gone, I use to do it loooong time ago with 0.3.7 version, you know when cmissync was still sparkleshare ;)

Anyway, thanks for your fast answer.

**Comment by nicolas-raoul** [comment]
So the problem is gone? Cheers! :-)

**Comment by antton** [comment]
Yes! Thanks.

2015-11-13 10:07 GMT+01:00 Nicolas Raoul <notifications@github.com>:
