### ISSUE TITLE
Browse remote folder on Mac

### ISSUE THREAD

**Issue by monker1980** [aegif/CmisSync#389]
The link generated by 'Browse remote folder' is invalid on the Mac client.

The link is generated like:

http://alfresco.mysite.com/share/page/site/mySite/documentlibrary%23filter=path%7C%252FManuals%252FHardware

When it should be like:

http://alfresco.mysite.com/share/page/site/mySite/documentlibrary#filter=path%7C%252FManuals%252FHardware

Seems like the %23 should be a #

**Comment by aleskinen** [comment]
This problem still exists in 2.3.3 version.

**Comment by nicolas-raoul** [comment]
Should be solved when #555 is solved.
