### ISSUE TITLE
Mac: File upload takes forever

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#454]
20 MB file, 2 hours have passed, still waiting.

Stuck at `requestStream.Close()` in https://github.com/OpenDataSpace/chemistry-dotcmis/blob/trunk/DotCMIS/binding/http.cs

It was not happening a few weeks ago.
Maybe due to the DotCMIS update?

**Comment by felfert** [comment]
Good news:
After complaining to Miguel personally, finally someone merged my fix into mono's master.
Now, it's just a matter of time waiting for the next release...

**Comment by nicolas-raoul** [comment]
Wonderful!
Thank you for the hard work.
So, any version higher than 3.12.0 should have it, if I understand correctly?

**Comment by felfert** [comment]
Exactly that is my understanding as well. Of course, I can't make any promises since I'm not a core member of the mono project ;)

**Comment by felfert** [comment]
Just a short heads up:
On Friday, they released RPMs and Debian packages of mono 3.12.1 and
guess what? Our fix still is not in there :-(

So:
For the Nth time, I am rebuilding everything in our repo at OBS...

Feel free to use this as a replacement (if the build is ready - still building ATM):
https://build.opensuse.org/package/show/home:ods/mono-core

Cheers
 -Fritz

**Comment by nicolas-raoul** [comment]
Incredible! :-/
Thanks for the heads up, and for the replacement package!
