### ISSUE TITLE
UpdateFile does not set changeToken

### ISSUE THREAD

**Issue by linzhixing** [aegif/CmisSync#516]
setContentStream method on CMIS server called from SynchronizedFolder#UpdateFile doesn't set changeToken. This could cause an update conflict error on the part of the CMIS server.

Tested with NemakiWare(2.0beta4) and the latest CmisSync on Windows 7(64bit) SP1.

Here is the related error logs:
```java
2015-01-20 01:19:24,107 [12] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not update file: C:\Users\linzhixing\CmisSync\localhost\bedroom\test_01.txt
DotCMIS.Exceptions.CmisConstraintException: Conflict
   場所 DotCMIS.Binding.AtomPub.ObjectService.SetContentStream(String repositoryId, String& objectId, Nullable`1 overwriteFlag, String& changeToken, IContentStream contentStream, IExtensionsData extension) 場所 c:\Users\linzhixing\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:行 2124
   場所 DotCMIS.Client.Impl.Document.SetContentStream(IContentStream contentStream, Boolean overwrite, Boolean refresh) 場所 c:\Users\linzhixing\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:行 907
   場所 CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UpdateFile(String filePath, IDocument remoteFile) 場所 c:\Users\linzhixing\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:行 1381
```

Debugging CmisSync, changeToken seems not to be set from  Ln1431
```java
 foreach (ICmisObject obj in remoteFolder.GetChildren())
```
NemakiWare requires changeToken for any update-like method.

**Comment by nicolas-raoul** [comment]
Does the CMIS specification say we must provide a changeToken at every write operation, for instance when calling `remoteFile.SetContentStream` or similar?

**Comment by linzhixing** [comment]
The specification 2.2.1.3. says

>If a repository provides a value for the cmis:changeToken property for an object, then all invocations of the "update" methods on that object (updateProperties, bulkUpdateProperties, setContentStream, appendContentStream, deleteContentStream, etc.) MUST provide the value of the cmis:changeToken property as an input parameter, and the repository MUST throw an updateConflictException if the value specified for the change token does NOT match the change token value for the object being updated.

At least NemakiWare expose cmis:changeToken as each object's property as well as in the change logs.

**Comment by nicolas-raoul** [comment]
OK thanks! :-)

**Comment by nicolas-raoul** [comment]
Fixed in https://bitbucket.org/aegif/cmissync/downloads/CmisSync.2.1.6.0.exe
