### ISSUE TITLE
Ubuntu build CmisSync ChangeLogThenCrawlSync does not exist in current context

### ISSUE THREAD

**Issue by scisys-bonsor-s** [aegif/CmisSync#526]
Attempted to follow linux build instructions for Ubuntu 14.04
git clone of Bumped version 2.2.1
mono version - 3.2.8 

Output of make
 make
Making all in build
make[1]: Entering directory `/home/vagrant/CmisSync/build'
Making all in m4
make[2]: Entering directory `/home/vagrant/CmisSync/build/m4'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/vagrant/CmisSync/build/m4'
make[2]: Entering directory `/home/vagrant/CmisSync/build'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/vagrant/CmisSync/build'
make[1]: Leaving directory `/home/vagrant/CmisSync/build'
Making all in CmisSync.Auth
make[1]: Entering directory `/home/vagrant/CmisSync/CmisSync.Auth'
/usr/bin/dmcs \
                 \
                 \
                 \
                -codepage:utf8 \
                -nowarn:0278 -nowarn:0078 $warn \
                -define:HAVE_GTK_2_10 -define:NET_2_0 \
                -debug -target:library -out:../bin/CmisSync.Auth.dll \
                -define:HAVE_APP_INDICATOR -define:ENABLE_ATK \
                 -r:../Extras/DotCMIS.dll -r:Mono.Posix.dll -r:System.Data.dll,Mono.Data.Sqlite.dll -r:System.Web.dll -r:/usr/lib//cli/log4net-1.2/log4net.dll -r:/usr/lib/cli/Newtonsoft.Json-5.0/Newtonsoft.Json.dll  ./Auth.cs ./Credentials.cs ./Crypto.cs ./Password.cs ./Properties/AssemblyInfo.cs
make[1]: Leaving directory `/home/vagrant/CmisSync/CmisSync.Auth'
Making all in CmisSync.Lib
make[1]: Entering directory `/home/vagrant/CmisSync/CmisSync.Lib'
/usr/bin/dmcs \
                 \
                 \
                 \
                -codepage:utf8 \
                -nowarn:0278 -nowarn:0078 $warn \
                -define:HAVE_GTK_2_10 -define:NET_2_0 \
                -debug -target:library -out:../bin/CmisSync.Lib.dll \
                -define:HAVE_APP_INDICATOR -define:ENABLE_ATK \
                 -r:../bin/CmisSync.Auth.dll -r:../Extras/DotCMIS.dll -r:Mono.Posix.dll -r:System.Data.dll,Mono.Data.Sqlite.dll -r:System.Web.dll -r:/usr/lib//cli/log4net-1.2/log4net.dll -r:/usr/lib/cli/Newtonsoft.Json-5.0/Newtonsoft.Json.dll  ./ActivityListenerAggregator.cs ./Backend.cs ./ChunkedStream.cs ./Cmis/BaseException.cs ./Cmis/PermissionDeniedException.cs ./Cmis/CmisUtils.cs ./Cmis/ServerNotFoundException.cs ./Cmis/MimeType.cs ./Config.cs ./ConfigManager.cs ./ConfigMigration.cs ./Database/Database.cs ./Database/DatabaseMigration.cs ./Database/DatabaseMigrationBase.cs ./Database/DatabaseMigrationToVersion3.cs ./Events/ActiveActivitiesManager.cs ./Events/ConfigChangedEvent.cs ./Events/DebugLoggingHandler.cs ./Events/FileConflictEvent.cs ./Events/FileTransmissionEvent.cs ./Events/FSDeletionHandler.cs ./Events/FSEvent.cs ./Events/GenericSyncEventHandler.cs ./Events/ISyncEvent.cs ./Events/SyncEventHandler.cs ./Events/SyncEventManager.cs ./Events/SyncEventQueue.cs ./IActivityListener.cs ./FolderLock.cs ./RepoBase.cs ./RepoInfo.cs ./SyncItem.cs ./Sync/ChangeLogStrategy.cs ./Sync/CmisRepo.cs ./Sync/CrawlStrategy.cs ./Sync/SynchronizedFolder.cs ./Sync/WatcherStrategy.cs ./UserNotificationListener.cs ./Utils.cs ./Watcher.cs ./Defines.cs
./Cmis/CmisUtils.cs(55,91): warning CS3001: Argument type `CmisSync.Auth.ServerCredentials' is not CLS-compliant
./Cmis/CmisUtils.cs(151,83): warning CS3001: Argument type `CmisSync.Auth.ServerCredentials' is not CLS-compliant
./Cmis/CmisUtils.cs(302,71): warning CS3001: Argument type `CmisSync.Auth.CmisRepoCredentials' is not CLS-compliant
./RepoInfo.cs(56,25): warning CS3003: Type of `CmisSync.Lib.RepoInfo.Password' is not CLS-compliant
./SyncItem.cs(41,32): warning CS3005: Identifier `CmisSync.Lib.SyncItem.LocalPath' differing only in case is not CLS-compliant
./SyncItem.cs(18,26): (Location of the symbol related to previous warning)
./SyncItem.cs(47,32): warning CS3005: Identifier `CmisSync.Lib.SyncItem.RemotePath' differing only in case is not CLS-compliant
./SyncItem.cs(21,26): (Location of the symbol related to previous warning)
./Sync/SynchronizedFolder.cs(328,25): warning CS3005: Identifier `CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.IsSyncing()' differing only in case is not CLS-compliant
./Sync/SynchronizedFolder.cs(320,25): (Location of the symbol related to previous warning)
./Sync/CrawlStrategy.cs(267,70): warning CS0168: The variable `e' is declared but never used
./Sync/SynchronizedFolder.cs(420,29): error CS0103: The name `ChangeLogThenCrawlSync' does not exist in the current context
Compilation failed: 1 error(s), 8 warnings
make[1]: *** [../bin/CmisSync.Lib.dll] Error 1
make[1]: Leaving directory `/home/vagrant/CmisSync/CmisSync.Lib'
make: *** [all-recursive] Error 1

**Comment by nicolas-raoul** [comment]
Fixed, thanks for reporting!
