### ISSUE TITLE
Problems trying to build on Fedora 21

### ISSUE THREAD

**Issue by Momar-DIENE** [aegif/CmisSync#543]
hi,
The message error is: "/home/mdiene/Bureau/CmisSync-master/CmisSync-master /CmisSync/Linux/CSC: Error CS2001: Source file `Defines.cs' could not be found (CS2001) (CmisSync)".

**Comment by nicolas-raoul** [comment]
Hello Momar,

Did you follow the instructions at https://github.com/aegif/CmisSync/blob/master/CmisSync/Linux/README.md ?
In particular the submodule/make/configure/etc steps.
Define.cs is created by these steps.

Also, please update as I pushed some important changes just now, thanks :-)

**Comment by Momar-DIENE** [comment]
Right the git's command doesn't work when i have doing "git submodule init" but after doing "git init" it works fine!
The confgure's command show this error: "newtonsoft-json is a required dependency: you need to install the appropriate devel package before you can compile" and I add the dependency with: "--with-newtonsoft-json=Extras/OpenDataSpaceDotCMIS/Newtonsoft.Json.dll " and i meet another error: "notify-sharp is a required dependency: you need to install the appropriate devel package before you can compile" whereas the package notify-sharp-develop is already installed. Finally the make's command fail.

**Comment by nicolas-raoul** [comment]
"git submodule init" is really important, "git init" is not the same thing.

Could you delete everything, restart the whole procedure, and post a screenshot of the whole terminal at the first error? Thanks!

**Comment by Momar-DIENE** [comment]
git submodule init works now

**Comment by Momar-DIENE** [comment]
Screenshot after the make command:
![capture](https://cloud.githubusercontent.com/assets/11393600/6981534/9ce42e66-d9f2-11e4-8227-f2825b49b5ad.PNG)

**Comment by nicolas-raoul** [comment]
You don't have the latest version.

Please run "git pull" and redo everything again.

Thanks!

**Comment by Momar-DIENE** [comment]
Yes with Cmissync-master the error is:
![capture2](https://cloud.githubusercontent.com/assets/11393600/6981674/6d8fcb18-d9f5-11e4-8aba-eb66c4adb005.PNG)

**Comment by nicolas-raoul** [comment]
You have an old CmisSync. This error was fixed 6 hours ago.

1) Delete everything
2) git clone again
3) do everything as explained in the README again

**Comment by nicolas-raoul** [comment]
Hi Momar,
Is it working better now?

**Comment by Momar-DIENE** [comment]
Hi nicolas,

Indeed I have met another problem:

![capture3](https://cloud.githubusercontent.com/assets/11393600/7020459/a862b848-dd08-11e4-8645-7b3660bb1786.PNG)
![capture4](https://cloud.githubusercontent.com/assets/11393600/7020462/ad119292-dd08-11e4-87de-8e26e4d7b40c.PNG)
![capture5](https://cloud.githubusercontent.com/assets/11393600/7020464/b1a39e36-dd08-11e4-8465-29954630965f.PNG)

**Comment by nicolas-raoul** [comment]
You did not delete everything.

Please run this command:
```
rm -rf /home/mdiene/Bureau/CmisSync-master*
```
Then perform the instructions described at https://github.com/aegif/CmisSync/blob/master/CmisSync/Linux/README.md

**Comment by Momar-DIENE** [comment]
I used the zip file source  code. I have delete all files with your command and I have redownload it. It's not ok.

![capture6](https://cloud.githubusercontent.com/assets/11393600/7022292/badf8198-dd19-11e4-870f-5de3b7f5a0c9.PNG)

**Comment by nicolas-raoul** [comment]
Could you please post the whole log? Thanks!
You can copy-paste here, see [the Syntax highlighting section here](https://guides.github.com/features/mastering-markdown)

**Comment by Momar-DIENE** [comment]
Ok Thanks for Markdown. The whole log:

![image](https://cloud.githubusercontent.com/assets/11393600/7022842/b220d3f8-dd1f-11e4-86ce-98ab664c1023.png)
![image](https://cloud.githubusercontent.com/assets/11393600/7022857/e8effd1e-dd1f-11e4-90d0-98a77fcb5e2c.png)
![image](https://cloud.githubusercontent.com/assets/11393600/7022881/1a091804-dd20-11e4-882e-6e89c0ec7526.png)
![image](https://cloud.githubusercontent.com/assets/11393600/7022911/563c9882-dd20-11e4-8e50-e81bf7a836d7.png)

**Comment by nicolas-raoul** [comment]
Your `./configure` line looks different from the instructions: https://github.com/aegif/CmisSync/blob/master/CmisSync/Linux/README.md

The log should say `checking for LOG4NET... yes` but yours say `checking for LOG4NET... no`.

Could you please run `sudo yum install liblog4net-cil` and try again? Does it work better?

**Comment by Momar-DIENE** [comment]
**which is it repository? Because it's avalaible!**
[mdiene@localhost CmisSync-master]$ sudo yum install liblog4net-cil
Modules complémentaires chargés : langpacks
Aucun paquet liblog4net-cil disponible.
Erreur : Rien à faire
[mdiene@localhost CmisSync-master]$

**Comment by nicolas-raoul** [comment]
Could you please try `sudo yum install log4net-devel` instead?

**Comment by Momar-DIENE** [comment]
Yes this is *ok* now!
Thank's a lot

![image](https://cloud.githubusercontent.com/assets/11393600/7023722/e54f5e5a-dd26-11e4-81fb-8bd15783dfa2.png)

**Comment by nicolas-raoul** [comment]
Génial :-)
