### ISSUE TITLE
Microsoft Word re-creates file, so CmisSync does the same, which results in history loss

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#553]
https://support.microsoft.com/en-us/kb/211632

```
Create temp file                     Create ~wrdxxxx.tmp
Write temp file                      Save data to ~wrdxxxx.tmp
Delete original file                 Delete Example.doc
Move temp to target name             Move ~wrdxxxx.tmp to Example.doc
```

**Comment by nicolas-raoul** [comment]
Solved (as much as we can possibly do, I guess) in CmisSync 2.4

**Comment by tgeens** [comment]
Could you elaborate on your strategy to cope with this ?

**Comment by nicolas-raoul** [comment]
@tgeens Sorry for the delay!

When a deletion happens, we just wait 15 seconds and sync, instead of instantly deleting the remote document.

Commit: https://github.com/aegif/CmisSync/commit/5ba5419445d6dfd828be28acf0a00651619201f3

15 seconds is arbitrary, not too long to wait and should be enough for even big documents to get saved.

Any better idea is welcome :-)
Cheers!
Nicolas
