### ISSUE TITLE
Problem to add new class

### ISSUE THREAD

**Issue by Momar-DIENE** [aegif/CmisSync#554]
I started developing CmisSync. All installations are done well.
However I meet an issue when i add a new class in the project. Monodevelop don't show errors when I build the project but In command line I have an error after the command **make**. The screenshot:

![image](https://cloud.githubusercontent.com/assets/11393600/7513162/90d4805c-f4a1-11e4-905f-083f1b18965e.png)
Like you see it, the message error is: **"./GUI.cs(30,10): error CS0246: The type or namespace name `SyncSize' could not be found. Are you missing an assembly reference?"**
**SyncSize** is the new class created and it is in the namespace **CmisSync**.

**Comment by nicolas-raoul** [comment]
Hello!
Could you please push your modified code to Github?
I don't see your code now, but I guess you have forgotten to add your new class to one of the `Makefile.am` files.

"SyncSize" sounds interesting, what feature are implementing? Quota? Showing how much space the folder will take? Something else?

Cheers!

**Comment by Momar-DIENE** [comment]
I added a new branch but I think it doesn't work fine. What is the whole procedure to push it if i already have changes in my code?
I'm a beginner on the development with **c# and linux**. I didn't know that the new classes have to be add in **Makefile**. I did it and now it works.

"SyncSize" is a feature which implementing how much space the folder will take. Are there features at this level

However i was adding String in **Proprietes.resources.resx** and **Resources.Designer.cs** they aren't visible in my interface. Is it the same problem?

Cheers!

**Comment by nicolas-raoul** [comment]
You have to commit and then run `git push --all` I think.

"SyncSize" feature is a great idea! There is no such feature yet, so your contribution is very welcome :-)

Don't worry too much about `Proprietes.resources.resx`, just hard-code strings and we will fix them later when the feature works correctly.

**Comment by Momar-DIENE** [comment]
All right.
Thank you very much!
See you!
