### ISSUE TITLE
Problem to add a remote folder in ubuntu (after modifying CmisSync source code)

### ISSUE THREAD

**Issue by Momar-DIENE** [aegif/CmisSync#557]
Hi every body,
I have got Ubuntu 14.04 and I work with CmisSync 2.2.3.0 and mono --version is: **3.2.8**
When I add a new folder, i meet an issue after giving web address, user and password. **The stacktrace:**

```
Assertion at mini.c:6201, condition `vtable' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at CmisSync.Lib.Cmis.CmisUtils.GetRepositories (CmisSync.Auth.ServerCredentials) <0x0016f>
  at CmisSync.Lib.Cmis.CmisUtils.GetRepositoriesFuzzy (CmisSync.Auth.ServerCredentials) <0x00b3f>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x4b73d8]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f54e99e3340]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f54e9643f79]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f54e9647388]
	mono() [0x638575]
	mono() [0x6386b6]
	mono() [0x425d39]
	mono() [0x425ecb]
	mono() [0x4b845b]
	[0x40cbc166]

Debug info from gdb:

ptrace: Operation not permitted.
No threads.

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries used by your application.
```

Thanks to helping me!

**Comment by Momar-DIENE** [comment]
It's happens when I add news lines of code to the project. Even if I delete the news lines, the error persist.

**Comment by nicolas-raoul** [comment]
Does this error appear with unmodified CmisSync? (from CmisSync.com)
Or only with the version you compiled?

**Comment by Momar-DIENE** [comment]
It appears with my compiled version. But if i delete additions it persist.

**Comment by nicolas-raoul** [comment]
Did it happen the first time you compiled, before you modified anything?

**Comment by Momar-DIENE** [comment]
No, it didn't!

**Comment by Momar-DIENE** [comment]
Hi all,

Problem solved after deleting the folders **/home/"username"/.config, /home/"username"/CmisSync and /usr/local/lib/CmisSync** before compiling.

Thanks!

**Comment by nicolas-raoul** [comment]
Wonderful, good job :-)
Does not `make clean` do that?
