### ISSUE TITLE
Content remotely deleted if synced folder removed while CmisSync is running

### ISSUE THREAD

**Issue by lelmarir** [aegif/CmisSync#559]
If you create a synced folder (and let it sync) and then delete or rename it, cmisSync will think that you want to delete all the files.

Instead it should throw an error and only remove all the files if the synced folder exist but is empty

**Comment by nicolas-raoul** [comment]
Actually, CmisSync already does this like you explain:

https://github.com/aegif/CmisSync/wiki/Remove-a-synchronized-folder#manually

Is it correct?

**Comment by lelmarir** [comment]
ok, i don't think this behaviour is correct: if i remove the folder while cmissync is closed it should recreate it on next start or complain about, and ask what to do: **remove** the sync, **point to another folder** (maybe i have just renamed it) or **resync** it

Even so; if i remove or rename the folder while cmissync is running it does not remove the sync but it will remove all the files on the server (a bug, if the current behaviour is to remove the sync).
It should instead behave as the previous case and ask what to do

**Comment by nicolas-raoul** [comment]
I see, behaviour is buggy when removing the folder while CmisSync is running, indeed.

A difficult point: When deleting a big folder, the system usually starts by removing all leaves and sub-directories one-by-one. In this case, CmisSync can not know whether the user is deleting files willingly, or whether the whole folder is being deleted.

Thanks for your feedback!

**Comment by nicolas-raoul** [comment]
I also created this issue with your other idea: https://github.com/aegif/CmisSync/issues/560

**Comment by nicolas-raoul** [comment]
A first thing could be to make the folder read-only or lock it somehow.

**Comment by lelmarir** [comment]
this is definitely useful, but it might be tricky to achieve it
