### ISSUE TITLE
Impossible to sync a Nuxeo folder when not administrator

### ISSUE THREAD

**Issue by jbpotokar** [aegif/CmisSync#598]
Hello, 

I've been connecting to my nuxeo server with no problem using an admin login. The sync seems ok. 
But when I try the same opération with non admin user, it seems that I can't see the folder beyond the main one. 
Any idea ? 

Thx !

**Comment by nicolas-raoul** [comment]
Thanks for the feedback!
Could you please try to access the same content with CMIS Workbench, using the non-admin user?
Waiting for your feedback :-)

**Comment by jbpotokar** [comment]
Hi, 
So I've been downloading and installing CMIS Workbench. 
Try on the same server, first as an admin, and even though I don't really know what to expect, it seems ok (first I load repositories, then I log in). 
Try a non admin user, I get a po up error message "object not found:fe570298-00a2-4ce8-966e-9c62d55a9990". The loading of the directory went well, but I get the message while logging...

**Comment by nicolas-raoul** [comment]
This sounds like a bug in Nuxeo... could you please post a bug report to the [Nuxeo JIRA](https://jira.nuxeo.com/browse/NXP/?selectedTab=com.atlassian.jira.jira-projects-plugin:issues-panel) and post a link to your bug report?
Thanks a lot!
Nicolas

**Comment by nicolas-raoul** [comment]
Hello JB,
Are you still experiencing the problem?
Cheers!
Nicolas

**Comment by jbpotokar** [comment]
Hello, 

I've stopped trying !
So I guess you can close the post !

Regards !
