### ISSUE TITLE
CMISsync does not open on Mac

### ISSUE THREAD

**Issue by bobmaes** [aegif/CmisSync#619]
CmisSync will not open on my Mac, no setup wizard is started. MonoRuntime has been installed...OS version is Yosemite version 10.10.2.

A CmisSync folder is created (in grey), with just one file in it called “Lock”. This files seems to be empty.

Thanks four your valued help,

Bob

**Comment by antton** [comment]
Which version of cmissync? I'm working with Maverick and Yosemite with cmissync 2.3 or even 2.4 versions and everything is working fine.

**Comment by bobmaes** [comment]
Thank you 

I have version 2.2.3. After you mail which referred to versions 2.3 and 2.4, I dowloaded the latest 2.4.9.dmg but the problem persists…Strangely after opening the dmg file, cmisync version remains 2.2.3 ?

**Comment by nicolas-raoul** [comment]
Hello @bobmaes,

Thanks to @antton 's idea, we now know it seems like a version problem.

Could you please try the following:

1. Uninstall CmisSync
2. Reset everything as explained here: https://github.com/aegif/CmisSync/wiki/Reset-settings#how-to-reset-cmissync-settings-on-maclinux
3. Install the latest version
4. Let us know

Cheers!
Nicolas

**Comment by bobmaes** [comment]
Thank you Nicolas! That did it! CmisSync is up and running.

kr

Bob

**Comment by nicolas-raoul** [comment]
Wonderful! :-)
Thanks @antton too!
