### ISSUE TITLE
Kaspersky detects cmissync 2.5.9 as virus

### ISSUE THREAD

**Issue by antton** [aegif/CmisSync#620]
Hi, 

Kaspersky detect cmissync 2.5.9 as trojan PDM:Win32.Generic.Trojan.

Can you check what's going on with this new .exe file?

Thanks

**Comment by nicolas-raoul** [comment]
This happens often, it is a false positive.

Everytime the procedure to follow is to report the false positive to Kaspersky/Symantec. I just did that for 2.5.9, thanks for your feedback!

**Comment by nicolas-raoul** [comment]
Kaspersky from today does not seem to consider 2.5.9 as a virus anymore:
https://www.virustotal.com/en/file/867b7d6bbe4587f5ec916445d08cc8c207f0a201fb528c9edfc38ccd92eadc00/analysis/
Can you confirm that?

**Comment by antton** [comment]
I'll check it later!

**Comment by antton** [comment]
Everything all right you can close the issue ;)

**Comment by nicolas-raoul** [comment]
Thanks!
Whenever that happens again, don't hesitate to report false positives to Kaspersky (or Symantec/etc) by yourself, anyone can report false positives :-)

**Comment by antton** [comment]
I will do it next time! ;)

2015-10-09 9:33 GMT+02:00 Nicolas Raoul <notifications@github.com>:
