### ISSUE TITLE
Output username to the log after server information

### ISSUE THREAD

**Issue by antton** [aegif/CmisSync#624]
Hi, 

Is there any way to register this information in alfresco LOGS, I know that the cmissync version is not possible right now but what about the username?

Thanks!

**Comment by nicolas-raoul** [comment]
Good idea!
Would you mind writing a small patch for this? Should be easy :-)

**Comment by antton** [comment]
Hi Nicolas, 

I try to check where we could send the username on a http binding with the server, but I'm not able to do it, we could send it as part of the user agent but I think that is a horrible solution.

The real problem is that actually we are working with 65 different cmissync installations and almost all of them has and average of 3 or 4 syncronization folders, when the helpdesk people make the installations they usually forget to change the 5 seconds check on folders that's why my servers are getting exhausted, and I try to detect who is the user by IP and so on, but it's almost imposible to follow.

Would be nice username and if it's possible more information like remote sync path, but I don't know if it's too complicate, at least it is for me to develop.

Thanks.

**Comment by nicolas-raoul** [comment]
Ah, I understand now, you want to write to the Alfresco log, not the CmisSync log, I see. My last answer was mistaken.

For this situation, the best would be to use Alfresco's audit feature. That's one of the things audit is made for.
If this answer is enough, I guess I can close this issue? Cheers!
