### ISSUE TITLE
Permanent sync with deleting tmp files

### ISSUE THREAD

**Issue by Montagnard65** [aegif/CmisSync#626]
Hello,
I have CMISSYNC 2.5.9 on Windows 8.1, and I put a one day sync for my folders, but it seems I have a permanent sync with permanent warning messages which tell me CMIS Sync will delete .tmp files (I pu a example in the attached screenshot).
Is there a way to avoid this messages ?
Thanks
![tmp files sync](https://cloud.githubusercontent.com/assets/8189200/10480470/ae23e14c-726a-11e5-954e-79da0c0b4330.png)

**Comment by nicolas-raoul** [comment]
We will remove this popup.
By the way, I have two separate questions:

1) Was this .tmp file on your server in the first place? Or did CmisSync upload it?

2) Did you voluntarily delete this .tmp file on the Windows side?

**Comment by Montagnard65** [comment]
Hi Nicolas,
For the pop up, I think the best way is to let the user chose what he wants : display or not this windows for every deleting file.

For your others questions : 
1) I can't see this .tmp files locally or on the server. So I don't know if it's Alfresco (5.0.d) create it or not.
2) No, I don't touch this files; so it's CmisSync which manage this actions. You can see a extract of my Alfresco dashboard below (same day, activity in 4 hours) :
![tableau de bord](https://cloud.githubusercontent.com/assets/8189200/10507206/2c2460a8-731f-11e5-9492-6e0211b6b1ef.PNG)
3) I ask CMISSync to synchronise once a day, but the sync is permanent... Is there a way to fix that ?

**Comment by nicolas-raoul** [comment]
1) Thanks for the info!

2) Thanks for the info!

3) That's how CmisSync is designed. The polling interval is for reading from the server. Local changes are synchronized immediately. If you really need only one sync per day, please contact us at CmisSync@aegif.jp and we might be able to build a custom solution for you.

By the way, we just released 2.6.0 in which this anoying popup does not appear anymore.
Thanks for using CmisSync!
Nicolas
