### ISSUE TITLE
Error in connecting to a sharepoint library

### ISSUE THREAD

**Issue by knucie** [aegif/CmisSync#631]
Dear All, please help me solve a problem.

I am trying to sync a sharepoint location. The guidance gives me an instruction to add the following url: Microsoft SharePoint 2013 subsite: http://<host>/<subsite>/_vti_bin/cmis/rest?getRepositories (must activate CMIS individually for EACH site and subsite)

However, once I type in the required details, i am prompted an error that I am using an invalid url, but the reality is that I am using a correct URL. 

I managed to figure out that the problem lies in the fact the <host> url of our server begins with a number, e.g. "http://5starsltd:8080/Applications/_vti_bin/cmis/rest?getRepositories" , and CMISSYNC  will automatically reject anything starting with a number. if I type in just starsltd without the "5" then it will take the address and try to connect.

Do you have any idea how I could resolve this issued? I can connect to the sharepoint server by typing in "http://5starsltd:8080/Applications/" in any web browser without any problems. 

In advacnce many thanks.

![20151027175514219](https://cloud.githubusercontent.com/assets/15347844/10767394/9a1dea6a-7ce4-11e5-8df3-984fe1dc31c1.png)

![20151027175556102](https://cloud.githubusercontent.com/assets/15347844/10767405/a95372a2-7ce4-11e5-9dee-322219e0e3f6.png)

**Comment by knucie** [comment]
Dear All, the latest version CmisSync 2.6.3.0 resolves the above described issue! What a fantastic response by CmisSync team! Absolutely amazing! Thank you!

**Comment by nicolas-raoul** [comment]
No problem, we are glad the problem is fixed, please enjoy CmisSync :-)
