### ISSUE TITLE
Add new sync folders without assitant

### ISSUE THREAD

**Issue by antton** [aegif/CmisSync#633]
Hi, 
Is there anyway to add folders into config.xml and then change the password in any of this syncronized repositories?

I've to syncronize 65 different repositorie points  in one computer and I'd like to skip at least the assistant proccess, I'm going to do evenything against the same alfresco server so that's why I thought could be easier.

Thanks for all

**Comment by nicolas-raoul** [comment]
Hello Antton,

Yes, you can can add many synchronized folders automatically. Just:

1. Close CmisSync
2. Add XML elements to the config.xml file
3. Open CmisSync

I hope this answers your question.
Best regards,
Nicolas Raoul

**Comment by antton** [comment]
Hi Nicolas, 

Sorry for reopening the question but what about the password? 
If I let it empty the cmissync remove <folder></folder> part from the .xml. 

If I made a copy of the previous <folder></folder> with cmisync closed change the local path folder (that i didn't create yet and change the remote path., letting the other syncrhonized folder password, cmissync never opens it looks that is running but it doesn't work.

Any other advice?

**Comment by antton** [comment]
I gave another try and the solution is if I create the local folder first and then add the `<folder></folder>` into the xml.

Thanks for all!

**Comment by nicolas-raoul** [comment]
Ah, yes, you must create the root folder, too.

The password uses the official Windows function, so there are probably tools to generate such passwords, but clear-text is OK too (for now).
