### ISSUE TITLE
Ubuntu 14.04 Desktop cmissync 2.6.5 problems

### ISSUE THREAD

**Issue by antton** [aegif/CmisSync#640]
I just download 2.6.5 .deb and I'm getting on the following error.

Stale CmisSync PID file found, starting a new instance...
Starting CmisSync... Done.
ulhiadmin@txikie:/tmp$ FullPath:/home/ulhiadmin/.config/cmissync/config.xml

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at CmisSync.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at CmisSync.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 

Any advice?

**Comment by antton** [comment]
After installing sudo apt-get install libmono-system-core4.0-cil the error message dissapear.

But I'm not able to open cmissync on Desktop yet, at least following the Wiki information ;)

Thanks!

**Comment by antton** [comment]
But there are more...

2015-11-27 13:37:13,238 [-1230407744] INFO  CmisSync.Program [(null)] - Starting. Version: 2.6.5.0
2015-11-27 13:37:13,264 [-1230407744] INFO  CmisSync.Lib.FolderLock [(null)] - Creating folder lock file: /home/ulhiadmin/CmisSync
2015-11-27 13:37:13,307 [-1230407744] FATAL CmisSync.Program [(null)] - Exception in Program.Main
System.IO.FileNotFoundException: Could not load file or assembly 'appindicator-sharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=bcae265d1c7ab4c2' or one of its dependencies.
File name: 'appindicator-sharp, Version=0.2.0.0, Culture=neutral, PublicKeyToken=bcae265d1c7ab4c2'
  at CmisSync.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 

I think that appindicator-sharp version 0.2 is not available on Ubuntu 14.04.

Let us know :)

**Comment by antton** [comment]
Ok I get it working already.

We need to install libnotify0.4-cil libappindicator0.1-cil  libmono-system-core4.0-cil  and also as I read on a Wiki libmono-sqlite4.0-cil and libgtk2.0-cil

So Could be much better to update the Wiki.

We can close this issue!

**Comment by nicolas-raoul** [comment]
So, what should we write at the Ubuntu paragraph instead of the packages below? Let me know and I will update:

```
sudo apt-get install libappindicator0.1-cil-dev gtk-sharp2 mono-runtime mono-devel \
  monodevelop libndesk-dbus1.0-cil-dev nant libnotify-cil-dev libgtk2.0-cil-dev mono-mcs \
  mono-gmcs libwebkit-cil-dev intltool libtool libndesk-dbus-glib1.0-cil-dev \
  liblog4net-cil-dev libnewtonsoft-json-cil-dev gvfs
```

or you can update by yourself, just click the edit pencil at https://github.com/aegif/CmisSync/blob/master/CmisSync/Linux/README.md

**Comment by antton** [comment]
I will make all the installation and fix the wiki, i let you know.

**Comment by antton** [comment]
Hi @nicolas-raoul 
I was following https://github.com/aegif/CmisSync/wiki/How-to-install-CmisSync-on-Linux to make the installation, but If I install all the packages described on building from the source I think it works. In my opinion would be better only to install the necessary packages to make the .deb works.

I'll change the wiki later and let you know.

Thanks.

**Comment by nicolas-raoul** [comment]
Ah, you are right, for install only it should be less packages.
If libmono-sqlite4.0-cil and libgtk2.0-cil are not enough, please edit the wiki, that would be great, thanks! :-)

**Comment by antton** [comment]
Ready!
