### ISSUE TITLE
SharePoint shows some sites but not all

### ISSUE THREAD

**Issue by idand26** [aegif/CmisSync#651]
Hi 

i installed the software lest week and when i past the shareoint site address  ican't choos wich site/folder to sync i see only the default sharepoint site  and i have more site (5) the i can't see /snyc 

how can i see the all sites ?

**Comment by nicolas-raoul** [comment]
Is CMIS enabled for all sites and sub-sites individually?
See http://sharepoint.stackexchange.com/questions/59189/how-to-activate-and-use-cmis-for-a-sharepoint-2013-server

**Comment by idand26** [comment]
yes i was activated  the CMIS features for all sites and sub-sites  and i follow by the guide that you send me , i dont want that the sharepoint site will be accessible from outsite so i follow only by step  3 and 4
![cmis](https://cloud.githubusercontent.com/assets/16987723/12711500/2f6af5ec-c8c9-11e5-8671-2a4249616dd6.jpg)

**Comment by idand26** [comment]
Any suggestions how to solve the problem?

**Comment by nicolas-raoul** [comment]
Hello idand26,

Thank you for the screenshot!

The next thing to try is to see whether the site is visible in CMIS Workbench:
http://chemistry.apache.org/java/developing/tools/dev-tools-workbench.html
Please install this tool (free open source), and use it to connect to your server. Then send a screenshot showing how your content appears in the tool. Thank you!

**Comment by idand26** [comment]
when i try  to connect to cmis workbench i get this message 
![capture](https://cloud.githubusercontent.com/assets/16987723/13052415/712d3e88-d407-11e5-9633-32bb2939233d.JPG)

**Comment by nicolas-raoul** [comment]
What URL did you enter into CMIS Workbench?

**Comment by idand26** [comment]
my sharepoint site address  "http://tahal-doc" it`s available only from our LAN company

**Comment by nicolas-raoul** [comment]
In CMIS Workbench you have to enter your *CMIS URL*
Ask your SharePoint administrator (or SharePoint support) what the CMIS URL is and post it here, thanks!

**Comment by idand26** [comment]
ok , i found the cmis url address and when i add to  "add remote folder"  i can see now the site end the folder this issue solved

but now after this first scan that download the remote folder to local , if I add new documents/folder or just make change on file it don’t sync 

the status of  CmisSync is "file up to date" but nothing update
[debug_log.txt](https://github.com/aegif/CmisSync/files/132174/debug_log.txt)

**Comment by nicolas-raoul** [comment]
Could you please create a new issue about this? Thanks!

**Comment by idand26** [comment]
thanks
