### ISSUE TITLE
I want to know the Code that make CMIS run when the Windows Start

### ISSUE THREAD

**Issue by ahmedtolba1984** [aegif/CmisSync#689]
Hi @nicolas-raoul 
I want to How you make CMIS to run when the windows Start; Please, give me the code that do this behavior(run app when windows Start)

**Comment by ahmedtolba1984** [comment]
any help

**Comment by nicolas-raoul** [comment]
Sorry for the late answer, here is how to do:
https://www.howtogeek.com/208224/how-to-add-programs-files-and-folders-to-system-startup-in-windows-8.1/
