### ISSUE TITLE
can't compile CmisSync.console on Windows with VS2015

### ISSUE THREAD

**Issue by mathieuga** [aegif/CmisSync#715]
Hi,
I can't compile CmisSync.console on Windows with VS2015.
I issue on Mono.Posix and Mono.Data.Sqlite.

So i  
**\- drop Mono.Data.Sqlite.dll and Mono.Posix.dll in /Extras**
**\- update CmisSync.Lib\CmisSync.Lib.csproj** 

```
<Reference Include="Mono.Data.Sqlite">
    <HintPath>..\Extras\Mono.Data.Sqlite.dll</HintPath>
</Reference>
    <Reference Include="Mono.Posix">
    <HintPath>..\Extras\Mono.Posix.dll</HintPath>
</Reference>
```

**\- update CmisSync.Lib\DotCMIS.csproj** 

```
<Reference Include="Mono.Posix">
        <HintPath>..\..\Mono.Posix.dll</HintPath>
</Reference>
```

I also add x64 and x86 in CmisSync.Console\bin\Debug for solve 'SQLite.Interop.dll' load error

**Comment by nicolas-raoul** [comment]
Thank you for the feedback!
Would you mind sending a pull request?
Cheers!
Nicolas

**Comment by mathieuga** [comment]
I not lots of skill with Git  ...
I will try to send a pull request but be careful with my change.

**Comment by nicolas-raoul** [comment]
We are using Nuget now so I works much better :-)
