### ISSUE TITLE
Arch Linux - Compilation Error

### ISSUE THREAD

**Issue by errotu** [aegif/CmisSync#741]
I try to compile the CmisSync on an Arch system. I'm following the steps from: https://github.com/aegif/CmisSync/blob/master/CmisSync/Linux/README.md
Unfortunately, when I'm executing the command:
`./configure --with-dotcmis=Extras/DotCMIS.dll`

 I get the error message:

> configure: error: "newtonsoft-json is a required dependency: you need to install the appropriate devel package before you can compile"

Do you have any idea which dependency I have to install on Arch? I already installed "monodevelop".

**Comment by nicolas-raoul** [comment]
You have to find (or build) the newtonsoft-json package for your
distribution.
Good luck!

**Comment by errotu** [comment]
Thanks for the fast reply, Nicolas!
Unfortunately, I didn't find any newtonsoft-json package for arch (not in the given repositories nor in the AUR). Do you or anyone else have an idea how to install newtonsoft-json on arch?

**Comment by nicolas-raoul** [comment]
The easiest might be to download the DLL and put it in the folder where
arch puts DLLs.
I recommend you ask on an Arch forum.
Cheers!
Nicolas

**Comment by errotu** [comment]
I solved the problem by using:
``./configure --with-dotcmis=Extras/DotCMIS.dll --with-newtonsoft-json=Extras/Newtonsoft.Json.dll

Unfortunately, I ran in a new problem. Since it is not connected with this one, I will open a new issue. This one can be marked as solved.
