### ISSUE TITLE
Alfresco: skip "documentLibrary" folder

### ISSUE THREAD

**Issue by monicakumari** [aegif/CmisSync#748]
currently, when I sync the the alfresco, it creates path C:\Users\monica\sites\siteName\documentLibrary\foldersAndFiles.
being a developer, I want to customize the path, want to skip "documentLibrary" step, so that it becomes C:\Users\monica\sites\siteName\foldersAndFiles. 
I want to show only files and folders in the siteName directory. 
can anyone help me for this : where I have to make changes in the code, so that I can skip the documentLibrary step from the path.

thanks in advance.

**Comment by nicolas-raoul** [comment]
You can do this in the wizard, no need to change the source code :-)

In the wizard, after you select the folder to sync you get this screen: (pardon my French)
![screenshot from 2017-07-18 15-26-07](https://user-images.githubusercontent.com/99590/28303340-a362e808-6bcd-11e7-85db-4329502ea3c2.png)
Just remove the content of the first field and replace it with the folder name you want, for instance "siteName".

Thanks for using CmisSync!

**Comment by monicakumari** [comment]
![untitled](https://user-images.githubusercontent.com/26789477/28304069-bbeea296-6bb3-11e7-91f6-9cf60c7eab74.png)

I have synced alfresco localhost on desktop - a folder is created named "localhost" 
path : C:\Users\monica\Desktop\localhost\testsite - testSite is the site name in alfresco.
inside testSite there is documentLibrary folder and the data(files and folders) inside it.
path is : C:\Users\monica\Desktop\localhost\testsite\documentLibrary\testFolder

DocumentLibrary folder is by default. I want to show all the data directly just inside the site name. want to skip the documentLibrary.
now, path must be : **C:\Users\monica\Desktop\localhost\testsite\testFolder** - I want this path. I want to see all the data(testFolder) directly inside the testSite.

**Comment by monicakumari** [comment]
basically I want to skip the DocumentLibrary step. so that the data directly syncs inside the sitename

**Comment by nicolas-raoul** [comment]
Yes, you can do this by following the procedure described in my answer above.

**Comment by monicakumari** [comment]
Thank you Nicolas, but I think you are not able to understand my issue.
there is a "Sites" folder in alfresco, where all the sites resides which are created by a user. i have created a site "testSite" and a testSite named folder is created inside "Sites" .inside this there are multiple folders by default  - wiki , dataList, Discussion, documenLibrary, links. By Default, user stores the data inside documentLibrary folder.
 
when I sync the root folder "Sites" so that all the sites like testSite1, testSite2 etc will sync directly inside the root folder.
when I open the folder testSite1 (path : users\monica\desktop\sites\testSite1)- I got all the default folders - wiki , dataList, Discussion, documenLibrary, links.
and my data is in documentLibrary sub-folder (path : users\monica\desktop\sites\testSite1\DocumentLibrary\)

now, I want to skip this step so that I can have the all the data directly inside Sites (the root folder) - as I dont want to see the default folders wiki , dataList, Discussion, documenLibrary, links.
i want to see my testFolder inside the testSite directly (path should be - users\monica\desktop\sites\testSite1\testfolder)


I hope you understand my issue. 
I can create the root folder anywhere using the solution you provided me above. but I want to change the path inside the root folder I have synced.

**Comment by nicolas-raoul** [comment]
Ah, I see.
wiki/dataList/Discussion/links are not usable so no need to sync them, right?
So people always sync the documenLibrary of each site, rather than the whole site, which contains too many things.
How many sites do you want to sync?

**Comment by monicakumari** [comment]
yes, I just want to sync documentLibrary and synced data directly shown inside the site folder.
there could be multiple sites, I am a developer and want to customize this.
currently I have 7 sites and every site have wiki, dataList, Discussion, links and documentLibrary folders inside the siteName subfolder.

**Comment by nicolas-raoul** [comment]
How about synchronizing site1/documentLibrary as "site1", site2/documentLibrary as "site2", etc?
Rather than synchronizing "Sites" altogether.

**Comment by monicakumari** [comment]
I was trying to sync all sites together.

**Comment by monicakumari** [comment]
one by one syncing is a kind of time waste for the users. and they will not prefer selecting and syncing sites one by one.

**Comment by nicolas-raoul** [comment]
Indeed, it is not very convenient... in the sync loops you must check for this specific folder and skip it, and on the opposite add it when crawling locally... not very easy.
You might also want to avoid the case where a user creates a normal folder with the name "documentLibrary".

**Comment by monicakumari** [comment]
yes.
please tell me the name of the file where I have to make changes in the code. because I am trying to do this by past three days. and i am no  able to find where I should make changes.

**Comment by monicakumari** [comment]
if I sync one particular site, for this I already replaced the path accordingly.. but I am not able to do it for all the sites together.

**Comment by mathieuga** [comment]
Hi
For my project I have to change the right of my users.
So may be you can make a script for change the right on the server sid for skip the folder.

**Comment by monicakumari** [comment]
I am trying to do something like this - 
if (remoteFolderPath.Contains("/documentLibrary/"))
            {
                remoteFolderPath = remoteFolderPath.Replace("/documentLibrary/", "/");
            }
I have used the same concept to skip the path on cmissync tray where we have to select the remote folder. that worked. but in this case, it is not working. don't know.. may be I am putting this concept in wrong file or wrong place.
if anybody knows the solution, kindly let me know. 
thanks in advance.
