### ISSUE TITLE
restrict the cmisSync app.

### ISSUE THREAD

**Issue by monicakumari** [aegif/CmisSync#757]
Hello,
I am using CmisSync desktop app with alfresco. I want to restrict the app from working for the "viewer" role.
anybody have any idea about restricting CmisSync. how to do it ??

thanks in advance.

**Comment by nicolas-raoul** [comment]
CmisSync shows everything the user has the right to see.
So, if Alfresco lets the user see thedoc.pdf then thedoc.pdf will also be visible via CmisSync, obviously.
If you want thedoc.pdf  to not be visible by the user, then please remove all of the user's rights for that file.
Cheers!

**Comment by nicolas-raoul** [comment]
I guess I can close this?
Cheers! :-)

**Comment by monicakumari** [comment]
Yes. I was busy these days so was not able to test.
You can close it for now.

Thanks,
Monica
