### ISSUE TITLE
When rename a document (from client) CmisSync launch a conflict related the own user, as shows the image attached

### ISSUE THREAD

**Issue by Vikcen** [aegif/CmisSync#778]
![image](https://user-images.githubusercontent.com/52175321/60042741-b9670580-96be-11e9-9246-ee0fee05d629.png)

It says an unknown user added a file at the same time as you. It occurs always, being the same user that renamed the document.

Could you help us with that please?

Greetings.

**Comment by nicolas-raoul** [comment]
Thank you for reporting!
We are currently in the middle of a big refactoring, hopefully it will solve this problem.

**Comment by Vikcen** [comment]
Thanks a lot for the fast feedback!

Could be that the client (CmisSync) is not refreshing the object of the renamed document after the rename operation? something like this:

![image](https://user-images.githubusercontent.com/52175321/60172403-e1647f00-980c-11e9-853a-e92100abd2d2.png)

Also, this is the log im getting:

**CmisSync.Lib.Cmis.BaseException: Referencia a objeto no establecida como instancia de un objeto. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CheckLocalFile(String localFilePath, IFolder remoteFolder, IList`1 localFilenameTranslationOfExistingRemoteDocuments)
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CheckLocalFiles(String localFolder, IFolder remoteFolder, IList`1 localFilenameTranslationOfExistingRemoteDocuments)
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String remotePath, String localFolder)
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync()
   en CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass35_0.<.ctor>b__0(Object o, DoWorkEventArgs args)
   --- Fin del seguimiento de la pila de la excepción interna ---**

Could you do a simple test of rename a document within the synchronized folder from the client (CmisSync), that is connected against your cmis server, if you are getting the same problem?


Greetings and thank you.

**Comment by Vikcen** [comment]
No problem, the rename is working now, we had an issue in our server implementation.
